# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            'Narendra Acharya'
tagline:          ''
description:      'My personal site'
url:              http://nma83.github.io
baseurl:          /

author:
  name:           'Narendra Acharya'
  url:            https://twitter.com/narendra_m_a

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/nma83

